# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/nokia/PL2/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),PL2)

$(call add-radio-file-sha1-checked,radio/abl.img,e59e1e1bb0d88233cc54286b45368f164dbac668)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,0afdeba545a2d1a8f626baf7eb11ee62fc2aa880)
$(call add-radio-file-sha1-checked,radio/cda.img,41ad575f3a292d79b271788304da65278842120e)
$(call add-radio-file-sha1-checked,radio/cmnlib.img,d0ebbf66fc01dab62ffdf9824653a1bbc652e9b5)
$(call add-radio-file-sha1-checked,radio/cmnlib64.img,6ba34a07394bf70f5635910d75c43d93e77d1536)
$(call add-radio-file-sha1-checked,radio/devcfg.img,49711d22aca257708149f81f78805f1a4ab81245)
$(call add-radio-file-sha1-checked,radio/dsp.img,c991a83a1ea3e6a0c1572f3f8af8692c9a7b7cc1)
$(call add-radio-file-sha1-checked,radio/hidden.img,9f7103658b0209b74137d6cb7e39986e54b03c04)
$(call add-radio-file-sha1-checked,radio/hyp.img,041b61165d2f07bcfcad6cef0fdcdb073dc5fcf4)
$(call add-radio-file-sha1-checked,radio/keymaster.img,700acca34a5e8bf87d32b9fb5d8deee287acdc95)
$(call add-radio-file-sha1-checked,radio/mdtp.img,b186389906aa96087fe3b6e0f2bcc1d4054bd02d)
$(call add-radio-file-sha1-checked,radio/mdtpsecapp.img,f92aabbb63ca6403836e9e703185906aba119aab)
$(call add-radio-file-sha1-checked,radio/modem.img,7018171c898d930feca4a4fdec832db70e4cff70)
$(call add-radio-file-sha1-checked,radio/nvdef.img,385ac99962c736b8c45979ff6a45546616e1423b)
$(call add-radio-file-sha1-checked,radio/pmic.img,3e162de82744dc27e076e0157a448c40195741f6)
$(call add-radio-file-sha1-checked,radio/rpm.img,60659c361d942968a4fecca987450be364799059)
$(call add-radio-file-sha1-checked,radio/splash.img,19303cc0be62c8d0a3b4d7ddc8ee90ff8525058b)
$(call add-radio-file-sha1-checked,radio/systeminfo.img,9bbd4ed1f5b1ae6a4e94e3be0206af5d7dde42aa)
$(call add-radio-file-sha1-checked,radio/tz.img,7a6c27bfa66716b63c7b423ad9faa43205631bcc)
$(call add-radio-file-sha1-checked,radio/xbl.img,cf202d714d7baee3a76d364831ca9230cd5165fb)

endif
